# Generated by Django 2.0.2 on 2018-02-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0004_auto_20180210_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
