# Generated by Django 2.0.2 on 2018-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0005_auto_20180211_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='user',
        ),
        migrations.AddField(
            model_name='commentary',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
