# Generated by Django 2.0.2 on 2018-02-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0006_auto_20180217_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.Promotion'),
        ),
    ]
