# Generated by Django 2.0.2 on 2018-02-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0007_auto_20180217_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promociones.Promotion'),
        ),
    ]
